# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code Parts
email: 
description: > # this means to ignore newlines until "baseurl:"
  A blog about Kotlin, Apache Kafka and other Stuff

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://code.parts" # the base hostname & protocol for your site
product_id: code.parts
github_repository: casasprunes/codeparts
permalink: pretty
excerpt_separator: "<!--more-->"
sass:
  style: compressed
defaults:
  -
    scope:
      path:            "tag/**"
    values:
      sitemap:         false

# Build settings
markdown: kramdown
port: 4001
plugins:
  - jekyll-sitemap
  - jekyll-tidy

social:
  image: "/assets/photo.jpg"
  github: "https://github.com/casasprunes"
  linkedin: "https://www.linkedin.com/in/casasprunes"
  twitter: "https://twitter.com/casasprunes"
  twitter_user: "@casasprunes"

organization:
  name: "Code Parts"
  description: "A blog about Kotlin, Apache Kafka and other Stuff"
  logo: "/assets/logo.png"

authors:
  casasprunes: "Pau Casas Prunés"
