# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code Parts
email: 
description: > # this means to ignore newlines until "baseurl:"
  A personal project to share code with colleagues and workmates.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://code.parts" # the base hostname & protocol for your site
product_id: code.parts
github_repository: casasprunes/codeparts
permalink: pretty
excerpt_separator: "<!--more-->"
sass:
  style: compressed
jekyll_tidy:
  compress_html: false
defaults:
  -
    scope:
      path:            "tag/**"
    values:
      sitemap:         false

# Build settings
markdown: kramdown
port: 4001
plugins:
  - jekyll-sitemap
  - jekyll-tidy

social:
  github: "https://github.com/casasprunes"
  linkedin: "https://www.linkedin.com/in/casasprunes"
  twitter: "https://twitter.com/casasprunes"

author:
  name: "Pau Casas Prunés"
  description: "I am an experienced Software Engineer with 10+ years of strong hands-on experience in the JVM stack with Kotlin, Groovy and Java. Advocate and practitioner of Lean/Agile principles and best practices in Software Development like Pair Programming, TDD, Refactoring, Simple Design, Trunk Based Development, CI/CD among others."
  given_name: "Pau"
  family_name: "Casas Prunés"
  photo: "/assets/photo.jpg"

organization:
  name: "Code Parts"
  description: "A personal project to share code with colleagues and workmates."
  logo: "/assets/logo.png"
